#!/usr/bin/env python3
"""
setup_ngrok.py — One-time ngrok static domain setup.

Usage:
    python setup_ngrok.py --token <NGROK_AUTH_TOKEN>

What it does:
  1. Authenticates ngrok with your token.
  2. Calls the ngrok API to claim your free static domain
     (every free account gets exactly one — e.g. yourword-yourword-1234.ngrok-free.app).
  3. Saves NGROK_AUTH_TOKEN + NGROK_DOMAIN + PUBLIC_URL to .env.
  4. Rewrites run_tunnel.sh and run_tunnel.bat to use ngrok instead of cloudflared.

After running this once on your personal laptop, just start the server normally:
    ./start_server.sh   (macOS/Linux)
    .\\start_server.ps1  (Windows)
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parent
ENV_PATH = ROOT / ".env"
NGROK_API = "https://api.ngrok.com"


# ── helpers ────────────────────────────────────────────────────────────────────

def _find_ngrok() -> str:
    """Return path to the ngrok binary (pyngrok location or PATH)."""
    # pyngrok downloads it here
    candidate = Path.home() / "Library" / "Application Support" / "ngrok" / "ngrok"
    if candidate.exists():
        return str(candidate)
    # Windows pyngrok path
    candidate_win = Path.home() / "AppData" / "Local" / "ngrok" / "ngrok.exe"
    if candidate_win.exists():
        return str(candidate_win)
    # Fall back to PATH
    return "ngrok"


def _save_env_var(key: str, value: str) -> None:
    """Update or append KEY=value in .env."""
    line = f"{key}={value}\n"
    if ENV_PATH.is_file():
        lines = ENV_PATH.read_text(encoding="utf-8").splitlines(keepends=True)
        for i, l in enumerate(lines):
            if l.startswith(f"{key}=") or l.startswith(f"{key} ="):
                lines[i] = line
                ENV_PATH.write_text("".join(lines), encoding="utf-8")
                return
        lines.append(line)
        ENV_PATH.write_text("".join(lines), encoding="utf-8")
    else:
        ENV_PATH.write_text(line, encoding="utf-8")


def _api(token: str, method: str, path: str, **kwargs) -> dict:
    headers = {
        "Authorization": f"Bearer {token}",
        "Ngrok-Version": "2",
        "Content-Type": "application/json",
    }
    url = f"{NGROK_API}{path}"
    resp = httpx.request(method, url, headers=headers, timeout=15, **kwargs)
    resp.raise_for_status()
    return resp.json()


# ── core steps ─────────────────────────────────────────────────────────────────

def authenticate_ngrok(token: str, ngrok_bin: str) -> None:
    print(f"[1/4] Authenticating ngrok with token...")
    result = subprocess.run(
        [ngrok_bin, "config", "add-authtoken", token],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"      ERROR: {result.stderr.strip()}")
        sys.exit(1)
    print("      ✓ Authenticated")


def get_or_create_static_domain(token: str) -> str:
    print("[2/4] Fetching your free static domain from ngrok API...")
    # Check if one already exists
    data = _api(token, "GET", "/reserved_domains")
    domains = data.get("reserved_domains", [])
    free_domains = [d for d in domains if d.get("domain", "").endswith("ngrok-free.app")]

    if free_domains:
        domain = free_domains[0]["domain"]
        print(f"      ✓ Found existing static domain: {domain}")
        return domain

    # Create one (free tier allows exactly one ngrok-free.app domain)
    print("      No static domain found — creating one...")
    result = _api(token, "POST", "/reserved_domains", json={"domain": ""})
    domain = result.get("domain", "")
    if not domain:
        print("      ERROR: ngrok API did not return a domain. Check your account at https://dashboard.ngrok.com/domains")
        sys.exit(1)
    print(f"      ✓ Created static domain: {domain}")
    return domain


def save_to_env(token: str, domain: str) -> None:
    print("[3/4] Saving NGROK_AUTH_TOKEN, NGROK_DOMAIN, PUBLIC_URL to .env...")
    _save_env_var("NGROK_AUTH_TOKEN", token)
    _save_env_var("NGROK_DOMAIN", domain)
    _save_env_var("PUBLIC_URL", f"https://{domain}")
    print(f"      ✓ PUBLIC_URL=https://{domain}")


def rewrite_tunnel_scripts(domain: str, ngrok_bin: str) -> None:
    print("[4/4] Rewriting run_tunnel.sh and run_tunnel.bat to use ngrok...")

    sh = ROOT / "run_tunnel.sh"
    sh.write_text(
        f"""#!/usr/bin/env bash
# Auto-generated by setup_ngrok.py — uses ngrok static domain.
# Re-run setup_ngrok.py to change settings.

PROXY_PORT="${{PROXY_PORT:-8000}}"
NGROK_DOMAIN="${{NGROK_DOMAIN:-{domain}}}"
NGROK_BIN="${{NGROK_EXE:-{ngrok_bin}}}"

exec "$NGROK_BIN" http "$PROXY_PORT" --domain="$NGROK_DOMAIN" --log=stderr
""",
        encoding="utf-8",
    )
    sh.chmod(0o755)
    print(f"      ✓ run_tunnel.sh updated")

    bat = ROOT / "run_tunnel.bat"
    bat.write_text(
        f"""@echo off
:: Auto-generated by setup_ngrok.py — uses ngrok static domain.
:: Re-run setup_ngrok.py to change settings.

if "%PROXY_PORT%"=="" set PROXY_PORT=8000
if "%NGROK_DOMAIN%"=="" set NGROK_DOMAIN={domain}
if "%NGROK_EXE%"=="" set NGROK_EXE=ngrok

"%NGROK_EXE%" http %PROXY_PORT% --domain=%NGROK_DOMAIN% --log=stderr
""",
        encoding="utf-8",
    )
    print(f"      ✓ run_tunnel.bat updated")


# ── main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Set up ngrok static domain for local-llm-server.")
    parser.add_argument("--token", required=True, help="Your ngrok auth token (https://dashboard.ngrok.com/get-started/your-authtoken)")
    args = parser.parse_args()

    token: str = args.token.strip()
    ngrok_bin = _find_ngrok()

    print("\n=== ngrok static domain setup ===\n")

    authenticate_ngrok(token, ngrok_bin)
    domain = get_or_create_static_domain(token)
    save_to_env(token, domain)
    rewrite_tunnel_scripts(domain, ngrok_bin)

    print(f"""
=== Done! ===

Your permanent tunnel URL: https://{domain}

This URL is saved as PUBLIC_URL in .env and will show up in the Admin UI.
The tunnel scripts now use ngrok — just run ./start_server.sh as normal.

To use with Claude Code on any machine:
  export ANTHROPIC_BASE_URL=https://{domain}
  export ANTHROPIC_API_KEY=<your-api-key>
  claude
""")


if __name__ == "__main__":
    main()
